### ISSUE TITLE
Out of range error when using analyze.py

### ISSUE THREAD

**Issue by asadaizaz** [Tr4sHCr4fT/nestmap#1]
If I run analyze.py I get an error saying 
`File "C:\Users\Asad\Desktop\Pokemon go dev\account creator\nestmap\analyze.py", line 53, in <module>
    main()
  File "C:\Users\Asad\Desktop\Pokemon go dev\account creator\nestmap\analyze.py", line 49, in main
    if sys.argv[1] == 'export' and sys.argv[2] == 'csv':
IndexError: list index out of range`

**Comment by tcmaps** [comment]
please run `analyze.py export csv file.csv`
